CREATE TABLE user_info(
  IDX INT NOT NULL AUTO_INCREMENT,
  USER_EMAIL VARCHAR(500) NOT NULL,
  USER_PW VARCHAR(500) NOT NULL,
  NICKNAME VARCHAR(200) NOT NULL,
  BIRTH DATE NOT NULL,
  USER_PROFILE LONGBLOB,
  C_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(IDX)
);

CREATE TABLE card_data(
  IDX INT NOT NULL AUTO_INCREMENT,
  SENDER_NM VARCHAR(500) NOT NULL,
  RECEIVER_NM VARCHAR(500) NOT NULL,
  RECEIVER_IDX INT NOT NULL,
  CARD_MSG TEXT NOT NULL,
  C_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(IDX)
);

-- 이모티콘 등록시 1366 에러 방지용 character set 을 utf8mb4로 설정
ALTER DATABASE birthday_paper CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
ALTER TABLE card_data CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;